### PR TITLE
add support for Apple M1

### PR DESCRIPTION
**Pull request by MarDiehl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@isuruf: many thanks for your help.

Do you think that it makes sense to report the need for `  - openmpi  # [mpi == 'openmpi' and build_platform != target_platform]` in `meta.yaml`. It's a little bit confusing that openMPI needs it but MPICH not.

**Comment by MarDiehl** [comment]
@isuruf: I meant opening an issue. If the current situation is the best technical solution, I would suggest to address this in the documentation. I found https://conda-forge.org/blog/posts/2020-10-29-macos-arm64 and https://conda-forge.org which does not mentioning MPI and /docs/maintainer/knowledge_base.html is pretty silent.

**Comment by isuruf** [comment]
Sure, an issue or a PR to the docs would be good to have.

**Pull request merged**
