### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by MarDiehl**
- explicitly install 'make' (was not required before)
- damask3.mpie.de became damask.mpie.de

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
You can just copy the migration file https://github.com/conda-forge/damask-feedstock/blob/6bd94b2b57eaa7cecd07f0b538ba373bcf4818ea/.ci_support/migrations/python310.yaml

**Pull request closed without merging**
